FROM alpine

LABEL maintainer="Khary Sharpe <ksharpe@email.com>"

ADD beanstalkd/install.sh install.sh
RUN chmod +x install.sh && sh install.sh && rm install.sh

EXPOSE 11300

CMD beanstalkd -p 11300
